version: "3.9"

services:
  postgres:
    build: .
    container_name: ocr_postgres
    restart: always
    environment:
      POSTGRES_DB: ocr_db
      POSTGRES_USER: abcd
      POSTGRES_PASSWORD: abcd@12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
